method: dcgan_gn

gpu_id: 0

dataset: celeba
data_root: data/img_align_celeba_resize/gender
image_size: 64
batch_size: 128

zdim: 128
num_channel: 3

num_epoch: 30

optimizer_g:
  type: adam
  args:
    lr: 2e-4
    betas:
      - 0.5
      - 0.999

optimizer_d:
  type: adam
  args:
    lr: 1e-4
    betas:
      - 0.5
      - 0.999


