method: wgan_dcgan

gpu_id: 0

dataset: celeba
data_root: data/img_align_celeba_resize/gender
image_size: 64
batch_size: 128

zdim: 100
num_channel: 3

num_epoch: 30

optimizer_g:
  type: adam
  args:
    lr: 2e-4
    betas:
      - 0.5
      - 0.999

scheduler_g:
  type: MultiStepLr
  args:
    milestones:
      - 10
      - 15
    gamma: 0.1


optimizer_d:
  type: adam
  args:
    lr: 2e-4
    betas:
      - 0.5
      - 0.999

scheduler_d:
  type: MultiStepLr
  args:
    milestones:
      - 10
      - 15
    gamma: 0.1
